# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_auto_20170914_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='icon',
            field=models.FileField(default='toto', upload_to='appIcon', verbose_name='Application icon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='cryptoKey',
            field=models.CharField(max_length=200, verbose_name='Cryptographic key'),
        ),
    ]
