# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_auto_20170915_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='icon',
            field=models.ImageField(upload_to='appIcon', verbose_name='Application icon'),
        ),
    ]
