# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_auto_20170915_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Country code')),
                ('name', models.CharField(max_length=100, verbose_name='Country name')),
            ],
        ),
    ]
