# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0006_auto_20170915_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAdConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Application')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.Country')),
            ],
        ),
    ]
