# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0008_adplace_adtype_platform'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationadconfig',
            unique_together=set([('application', 'country')]),
        ),
    ]
