# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0009_auto_20170918_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='display',
            field=models.BooleanField(default=True, verbose_name='Display country'),
            preserve_default=False,
        ),
    ]
