# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0013_auto_20170926_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAdPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adPlace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.AdPlace')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationAdType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.AdType')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.ApplicationPlatform')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='applicationad',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='applicationad',
            name='adPlace',
        ),
        migrations.RemoveField(
            model_name='applicationad',
            name='adType',
        ),
        migrations.RemoveField(
            model_name='applicationad',
            name='platform',
        ),
        migrations.DeleteModel(
            name='ApplicationAd',
        ),
        migrations.AddField(
            model_name='applicationadplace',
            name='adType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.ApplicationAdType'),
        ),
        migrations.AddField(
            model_name='applicationadplace',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.ApplicationPlatform'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationadtype',
            unique_together=set([('platform', 'adType')]),
        ),
        migrations.AlterUniqueTogether(
            name='applicationadplace',
            unique_together=set([('platform', 'adType', 'adPlace')]),
        ),
    ]
